<?php require  'templates/header.phtml'; ?>
        <div class = "mt-5 w-25 mx-auto">
        <form method="POST" action="agregar">
            <h2>Agregar Cancion</h2>
         <label for="nombreCancion">Nombre de la Cancion</label>
         <input type="text" class="form-control" id="nombreCancion"  name = "nombreCancion">
         <label for="duracion">Duracion</label>
         <input type="text" class="form-control" id="duracion"  name = "duracion">
         <label for="genero">Genero</label>
         <input type="text" class="form-control" id="genero"  name = "genero">
         <label for="anio">Año</label>
         <input type="date" class="form-control" id="anio"  name = "anio">
         <select name ="album" id ="album">
            <?php   foreach ($albums as $album): ?>  
            <option value="<?=$album->IdAlbum?>"><?=$album->nombreAlbum?></option>
            <?php endforeach; ?>
         </select>
         <select name ="artista" >
            <?php   foreach ($albums as $album): ?>  
            <option value="<?=$album->IdArtista?>"><?=$album->nombreArtista?></option>
            <?php endforeach; ?>
         </select>
         <button type="submit" class="btn btn-primary mt-3">Agregar</button>
        </form>
        </div>