<?php require  'templates/header.phtml'; ?>
                <ul class="navbar-nav m-4">
                        <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="busqueda/<?= $genero='reggeton' ?>">Reggeton</a>
                        </li>
                                <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="busqueda/<?= $genero='trap' ?>">Trap</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="busqueda/<?= $genero='pop' ?>">Pop</a>
                        </li>
                </ul>


                <table class="table table-sm m-4">
            
<?php require  'templates/footer.phtml' ?>