<?php require  'templates/header.phtml'; ?>
echo "<h1>Lista por artista por : $nacionalidad</h1>";
          echo "<table>
          <thead>
              <tr>
                  <th>Título</th>
                  <th>Año</th>
                  <th>Estudio</th>
              </tr>
          <thead>
          <tbody>
          <table>
                    <thead>
                    <tr>
                    <th>Artista</th>
                    <th>Pais</th>
                    <th>Edad</th>
                </tr>
            <thead>
            <tbody>  
             <?php   foreach ($artistas as $artista): ?>      
                <tr>               
                    <td><?=$artista->nombreArtista?></td>
                    <td><?=$artista->nacionalidad?></td>
                    <td><?=$artista->edad?></td>
                </tr>
            
            <?php endforeach; ?>
             </tbody>      
            </table>      
             <?php require  'templates/footer.phtml' ?>
 

