<?php require  'templates/header.phtml'; ?>
     <h1 class="mx-auto"> Lista de Nuestras Canciones </h1>
                 <table class="table table-sm m-4">
                    <thead>
                    <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Duracion</th>
                    <th scope="col">Genero</th>
                    <th scope="col">Año de Lanzamiento</th>
                    <th scope="col">Album</th>
                    <th scope="col">Artista</th>

                </tr>
            <thead>
            <tbody>  
             <?php   foreach ($canciones as $cancion): ?>      
                <tr>               
                    <td><?=$cancion->nombreCancion?></td>
                    <td><?=$cancion->duracion?></td>
                    <td><?=$cancion->genero?></td>
                    <td><?=$cancion->anio?></td>
                    <td><?=$cancion->nombreAlbum?></td>
                    <td><?=$cancion->nombreArtista?></td>
                </tr>
            
            <?php endforeach; ?>
             </tbody>      
            </table>      
             <?php require  'templates/footer.phtml' ?>
 