<div class = "mt-5 w-25 mx-auto " >
        <form method="POST" action="delete">
            <h2>Eliminar Cancion </h2>
        <select name ="cancion">
          <?php   foreach ($canciones as $cancion): ?>   
          <option value="<?=$cancion->IdCancion?>"><?=$cancion->nombreCancion?></option>
          <?php endforeach; ?>
        </select>        
         <button type="submit" class="btn btn-primary mt-3">Eliminar</button>
        </form>
      </div>

<?php require_once 'templates/footer.phtml'; ?>