<!-- main footer -->
<footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
      <div class="align-items-center">
        <span class="text-muted">Follow Us</span>
        <a href="https://api.instagram.com/" target="_blank"><i class="bii bi-instagram text-black"></i></a>
        <a href="https://es-la.facebook.com/" target="_blank"><i class="bii bi-facebook text-black"></i></a>
        <a href="https://twitter.com/?lang=es" target="_blank"><i class="bii bi-twitter-x text-black"></i></a>
      </div>
</footer>
  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>