<?php require  'templates/header.phtml'; ?>
<div class = "mt-5 w-25 mx-auto">
<form method="POST" action="autenticar">
  <div class="form-group ">
    <label for="user">Usuario</label>
    <input type="text" class="form-control" id="user"  name = "user"aria-describedby="emailHelp" placeholder="Escriba Usuario">
    
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" name = "password" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-primary">Ingresar</button>
</form>
</div>
<?php require  'templates/footer.phtml' ?>
