<!-- formulario de alta de lista -->
<?php require  'templates/header.phtml'; ?>

<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <h2>My Playlist</h2>
        <div class="col-9">
            <div class="form-group">
                <label>Titulo</label>
                <input required name="titulo" type="text" class="form-control">
            </div>
        </div>
        </div>
    </div>
    <div class="col-9">
        <div class="form-group">
            <label>Artista</label>
            <input required name="artista" type="text" class="form-control">
        </div>
    </div>
    <div class="col-9">
        <div class="form-group">
            <label>Genero</label>
            <input required name="genero" type="text" class="form-control">
        </div>
    
    </div>
  </div>

  <button type="submit" class="btn btn-primary mt-2">Cargar</button>
</form>
        
