<?php require  'templates/header.phtml'; ?>
<h1 class="text-center mt-5">Bienvenidos a MUSICALLY </h1>
<div class = "d-flex mt-5 mb-5">
<img src="images/tini.jpg" class="rounded mx-auto d-block w-25" alt="...">
<img src="images/duki.png" class="rounded mx-auto d-block w-25" alt="...">
<img src="images/Bad-Bunny.jpg" class="rounded mx-auto d-block w-25" alt="...">
</div>


<?php require  'templates/footer.phtml' ?>